export type BetCard = {
  badge: string;
  type: string;
  match: string;
  market: string;
  odd: string;
  meta: string;
  confidence: string;
  stake: string;
  risk: string;
  slug: string;
  riskTone?: "red";
  status?: string;
  statusTone?: "win" | "loss" | "pending";
  score?: string;
};

export type TableRow = {
  id: number;
  pick: string;
  odd: string;
  confidence: string;
  stake: string;
};

export type BetDetail = {
  slug: string;
  match: string;
  title: string;
  market: string;
  type: string;
  odd: string;
  confidence: string;
  stake: string;
  risk: string;
  time: string;
  location: string;
  summary: string;
  keyPoints: string[];
  validation: string[];
  status?: string;
  finalScore?: string;
  outcomeNotes?: string[];
};

export const betCardsToday: BetCard[] = [
  {
    badge: "HOT",
    type: "Parlay 1 + Over 2.5",
    match: "Union Berlin vs RB Leipzig",
    market: "Vitória RB Leipzig + Over 2.5",
    odd: "1.70 - 1.95",
    meta: "16h30 · An der Alten Försterei",
    confidence: "85% confiança",
    stake: "Stake 4% banca",
    risk: "Risco Baixo-Médio",
    slug: "union-leipzig-parlay",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "HOT",
    type: "Moneyline",
    match: "Lecce vs Pisa",
    market: "Vitória Lecce",
    odd: "1.80 - 2.10",
    meta: "16h45 · Via del Mare",
    confidence: "82% confiança",
    stake: "Stake 3.5% banca",
    risk: "Risco Baixo-Médio",
    slug: "lecce-pisa",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "OK",
    type: "Parlay 1 + Over 2.5",
    match: "Real Sociedad vs Girona",
    market: "Vitória Sociedad + Over 2.5",
    odd: "1.75 - 2.05",
    meta: "17h00 · Reale Arena",
    confidence: "84% confiança",
    stake: "Stake 4% banca",
    risk: "Risco Baixo-Médio",
    slug: "sociedad-girona-parlay",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "OK",
    type: "Cartões",
    match: "Kasimpaşa vs Gençlerbirliği",
    market: "Over 4.5 cartões",
    odd: "1.65 - 1.85",
    meta: "14h00 · Recep Tayyip Erdoğan",
    confidence: "78% confiança",
    stake: "Stake 3% banca",
    risk: "Risco Médio",
    slug: "kasimpasa-genclerbirligi-cartoes",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "OK",
    type: "BTTS",
    match: "West Bromwich vs Sheffield United",
    market: "Ambos marcam",
    odd: "1.68 - 1.88",
    meta: "17h00 · The Hawthorns",
    confidence: "76% confiança",
    stake: "Stake 3% banca",
    risk: "Risco Baixo-Médio",
    slug: "wba-sheffield-btts",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "OK",
    type: "Escanteios",
    match: "Union Berlin vs RB Leipzig",
    market: "Over 9.5 escanteios",
    odd: "1.72 - 1.92",
    meta: "16h30 · An der Alten Försterei",
    confidence: "79% confiança",
    stake: "Stake 3% banca",
    risk: "Risco Baixo-Médio",
    slug: "union-leipzig-escanteios",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "ARROJADA",
    type: "Under Escanteios",
    match: "Lecce vs Pisa",
    market: "Under 10.5 escanteios",
    odd: "1.78 - 1.98",
    meta: "16h45 · Via del Mare",
    confidence: "74% confiança",
    stake: "Stake 2.5% banca",
    risk: "Risco Médio",
    slug: "lecce-pisa-under-corners",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "ARROJADA",
    type: "Marcador",
    match: "Raphinha (Brasil)",
    market: "Marcar a qualquer tempo",
    odd: "2.40 - 2.80",
    meta: "Contexto: amistoso/qualificador",
    confidence: "72% confiança",
    stake: "Stake 1% banca",
    risk: "Risco Médio-Alto",
    slug: "raphinha-marcador",
    status: "Não iniciado",
    statusTone: "pending",
    riskTone: "red",
  },
  {
    badge: "ARROJADA",
    type: "Primeira meta",
    match: "Real Sociedad marca 1º tempo",
    market: "Sociedad marca primeiro",
    odd: "1.80 - 2.00",
    meta: "17h00 · Reale Arena",
    confidence: "75% confiança",
    stake: "Stake 2% banca",
    risk: "Risco Médio",
    slug: "sociedad-primeiro-tempo",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "ARROJADA",
    type: "Clean Sheet",
    match: "RB Leipzig não sofre gols",
    market: "Leipzig clean sheet",
    odd: "1.95 - 2.25",
    meta: "16h30 · An der Alten Försterei",
    confidence: "73% confiança",
    stake: "Stake 2.5% banca",
    risk: "Risco Médio",
    slug: "leipzig-clean-sheet",
    status: "Não iniciado",
    statusTone: "pending",
  },
];

export const betCardsYesterday: BetCard[] = [
  {
    badge: "HOT",
    type: "Moneyline",
    match: "Fluminense vs Vasco",
    market: "Vitória Fluminense (Moneyline)",
    odd: "1.80 - 2.10",
    meta: "20h00 · Maracanã",
    confidence: "83% confiança",
    stake: "Stake 4% banca",
    risk: "Risco Baixo-Médio",
    slug: "fluminense-vasco",
    status: "Encerrado · ❌ Perdida",
    statusTone: "loss",
    score: "Vasco 2 x 1 Fluminense",
  },
  {
    badge: "HOT",
    type: "1 + Over 1.5",
    match: "Aston Villa vs Basel",
    market: "Vitória Aston Villa + Over 1.5",
    odd: "1.50 - 1.70",
    meta: "17h00 · St. Jakob Park",
    confidence: "86% confiança",
    stake: "Stake 5% banca",
    risk: "Risco Muito Baixo",
    slug: "aston-villa-basel",
    status: "Encerrado · ✅ Vencida",
    statusTone: "win",
    score: "Basel 1 x 2 Aston Villa",
  },
  {
    badge: "OK",
    type: "Moneyline",
    match: "Nottingham Forest vs Utrecht",
    market: "Vitória Nottingham Forest",
    odd: "1.65 - 1.90",
    meta: "14h45 · Galgenwaard",
    confidence: "79% confiança",
    stake: "Stake 3.5% banca",
    risk: "Risco Baixo-Médio",
    slug: "nottingham-utrecht",
    status: "Encerrado · ✅ Vencida",
    statusTone: "win",
    score: "Utrecht 1 x 2 Nottingham Forest",
  },
  {
    badge: "ARROJADA",
    type: "BTTS + Over 2.5",
    match: "Celtic vs Roma",
    market: "Ambos marcam + Over 2.5",
    odd: "1.85 - 2.15",
    meta: "17h00 · Celtic Park",
    confidence: "81% confiança",
    stake: "Stake 2% banca",
    risk: "Risco Médio",
    slug: "celtic-roma-btts",
    status: "Encerrado · ❌ Perdida",
    statusTone: "loss",
    score: "Celtic 0 x 3 Roma",
  },
  {
    badge: "HOT",
    type: "Moneyline",
    match: "Real Betis vs Dinamo Zagreb",
    market: "Vitória Betis",
    odd: "1.70 - 1.95",
    meta: "14h45 · Estádio Maksimir",
    confidence: "85% confiança",
    stake: "Stake 4% banca",
    risk: "Risco Baixo-Médio",
    slug: "betis-zagreb",
    status: "Encerrado · ✅ Vencida",
    statusTone: "win",
    score: "Dinamo Zagreb 1 x 3 Real Betis",
  },
  {
    badge: "OK",
    type: "1 + Over 2.5",
    match: "Flamengo vs Pyramids",
    market: "Vitória Flamengo + Over 2.5",
    odd: "1.45 - 1.65",
    meta: "14h00 · Ahmad Bin Ali (Neutro)",
    confidence: "78% confiança",
    stake: "Stake 3.5% banca",
    risk: "Risco Baixo-Médio",
    slug: "flamengo-pyramids",
    status: "Não iniciado",
    statusTone: "pending",
  },
  {
    badge: "PARLAY",
    type: "Cartões + Moneyline",
    match: "Dinamo Zagreb vs Betis",
    market: "Over 4.5 cartões + Vitória Betis",
    odd: "1.90 - 2.25",
    meta: "Árbitro Marko Gurglič · 14h45",
    confidence: "80% confiança",
    stake: "Stake 2% banca",
    risk: "Risco Médio",
    slug: "zagreb-betis-parlay",
    riskTone: "red",
    status: "Encerrado · ✅ Vencida (cartões 5-7 estim.)",
    statusTone: "win",
    score: "Betis 3-1; over 4.5 cartões",
  },
  {
    badge: "OK",
    type: "Marcador 1T",
    match: "Roma marca no 1º tempo",
    market: "Primeira meta da Roma",
    odd: "1.55 - 1.75",
    meta: "17h00 · Celtic Park",
    confidence: "76% confiança",
    stake: "Stake 3% banca",
    risk: "Risco Baixo-Médio",
    slug: "roma-primeiro-tempo",
    status: "Encerrado · ✅ Vencida",
    statusTone: "win",
    score: "Roma 3-0 no 1º tempo",
  },
  {
    badge: "ARROJADA",
    type: "Marcador",
    match: "Giovani Lo Celso (Roma)",
    market: "Marcar a qualquer momento",
    odd: "2.50 - 3.20",
    meta: "17h00 · Celtic Park",
    confidence: "84% confiança",
    stake: "Stake 1% banca",
    risk: "Risco Médio-Alto",
    slug: "lo-celso-marcador",
    riskTone: "red",
    status: "Encerrado · ❌ Perdida",
    statusTone: "loss",
    score: "Lo Celso não marcou",
  },
  {
    badge: "OK",
    type: "Escanteios",
    match: "Celtic vs Roma",
    market: "Over 9.5 escanteios",
    odd: "1.65 - 1.85",
    meta: "17h00 · Celtic Park",
    confidence: "77% confiança",
    stake: "Stake 3% banca",
    risk: "Risco Baixo-Médio",
    slug: "celtic-roma-escanteios",
    status: "Encerrado · ✅ Vencida",
    statusTone: "win",
    score: "Celtic 0-3 Roma; 11-12 cantos",
  },
];

export const tableRows: TableRow[] = [
  {
    id: 1,
    pick: "Union Berlin vs Leipzig - Vitória Leipzig + Over 2.5",
    odd: "1.70 - 1.95",
    confidence: "85%",
    stake: "4%",
  },
  {
    id: 2,
    pick: "Lecce vs Pisa - Vitória Lecce",
    odd: "1.80 - 2.10",
    confidence: "82%",
    stake: "3.5%",
  },
  {
    id: 3,
    pick: "Real Sociedad vs Girona - 1 + Over 2.5",
    odd: "1.75 - 2.05",
    confidence: "84%",
    stake: "4%",
  },
  {
    id: 4,
    pick: "Kasimpaşa vs Gençlerbirliği - Over 4.5 cartões",
    odd: "1.65 - 1.85",
    confidence: "78%",
    stake: "3%",
  },
  {
    id: 5,
    pick: "WBA vs Sheffield United - Ambos marcam",
    odd: "1.68 - 1.88",
    confidence: "76%",
    stake: "3%",
  },
  {
    id: 6,
    pick: "Union Berlin - Over 9.5 escanteios",
    odd: "1.72 - 1.92",
    confidence: "79%",
    stake: "3%",
  },
  {
    id: 7,
    pick: "Lecce vs Pisa - Under 10.5 escanteios",
    odd: "1.78 - 1.98",
    confidence: "74%",
    stake: "2.5%",
  },
  {
    id: 8,
    pick: "Raphinha marcar (Brasil)",
    odd: "2.40 - 2.80",
    confidence: "72%",
    stake: "1%",
  },
  {
    id: 9,
    pick: "Real Sociedad marca 1º tempo",
    odd: "1.80 - 2.00",
    confidence: "75%",
    stake: "2%",
  },
  {
    id: 10,
    pick: "RB Leipzig clean sheet",
    odd: "1.95 - 2.25",
    confidence: "73%",
    stake: "2.5%",
  },
];

export const betDetails: Record<string, BetDetail> = {
  "union-leipzig-parlay": {
    slug: "union-leipzig-parlay",
    match: "Union Berlin vs RB Leipzig",
    title: "RB Leipzig + Over 2.5",
    market: "Parlay vitória Leipzig + Over 2.5",
    type: "Conservadora",
    odd: "1.70 - 1.95",
    confidence: "85%",
    stake: "4%",
    risk: "Baixo-Médio",
    time: "16h30",
    location: "An der Alten Försterei, Berlim",
    summary: "Leipzig vive fase forte (2º Bundesliga) com ataque de 1.5 g/jogo e enfrenta Union instável e com defesa vulnerável.",
    keyPoints: [
      "Disparidade técnica 500M+ vs 100M; Leipzig precisa vencer para seguir no topo.",
      "Union sofre 1.3 g/jogo; Leipzig marca 1.5+ g/jogo.",
      "Histórico favorável ao Leipzig (75% de aproveitamento).",
    ],
    validation: [
      "Escalação oficial confirmada; manter parlay se linha de gols ≥2.5.",
      "Stake 4% com stop-loss diário 12%.",
    ],
    status: "Não iniciado",
  },
  "lecce-pisa": {
    slug: "lecce-pisa",
    match: "Lecce vs Pisa",
    title: "Vitória Lecce",
    market: "Moneyline Lecce",
    type: "Conservadora",
    odd: "1.80 - 2.10",
    confidence: "82%",
    stake: "3.5%",
    risk: "Baixo-Médio",
    time: "16h45",
    location: "Via del Mare, Lecce",
    summary: "Lecce forte em casa (3V em 5) enfrenta Pisa visitante fraco e em zona de rebaixamento.",
    keyPoints: [
      "Lecce em casa sofre só 0.8 g/jogo; Pisa fora 0.4 ponto/jogo.",
      "Momento: Lecce 3V/5 em casa; Pisa 1V/7 fora.",
      "Histórico favorável e torcida empurrando (25k).",
    ],
    validation: [
      "Checar desfalques de última hora; manter stake 3.5%.",
      "Aplicar Kelly 0.25 e stop-loss 12%.",
    ],
    status: "Não iniciado",
  },
  "sociedad-girona-parlay": {
    slug: "sociedad-girona-parlay",
    match: "Real Sociedad vs Girona",
    title: "Sociedad + Over 2.5",
    market: "Parlay vitória + Over 2.5",
    type: "Conservadora",
    odd: "1.75 - 2.05",
    confidence: "84%",
    stake: "4%",
    risk: "Baixo-Médio",
    time: "17h00",
    location: "Reale Arena, San Sebastián",
    summary: "Sociedad dominante em casa (65% posse) encara Girona abalado por goleada, com defesa vazando 1.4 g/jogo fora.",
    keyPoints: [
      "Sociedad 73% aproveitamento em casa; Girona 1V nas últimas 5 fora.",
      "Linha de gols apoiada em ofensiva de 1.27 g/jogo (Sociedad) vs 1.4 sofridos (Girona).",
      "Pressão de recuperação pós-derrota do Girona favorece ritmo alto de gols.",
    ],
    validation: [
      "Confirmar XI inicial; manter parlay se linha gols ≥2.5.",
      "Stake 4% alinhada a confiança 84%.",
    ],
    status: "Não iniciado",
  },
  "kasimpasa-genclerbirligi-cartoes": {
    slug: "kasimpasa-genclerbirligi-cartoes",
    match: "Kasimpaşa vs Gençlerbirliği",
    title: "Over 4.5 cartões",
    market: "Mais de 4.5 cartões",
    type: "Conservadora",
    odd: "1.65 - 1.85",
    confidence: "78%",
    stake: "3%",
    risk: "Médio",
    time: "14h00",
    location: "Recep Tayyip Erdoğan, Istambul",
    summary: "Super Lig com média alta de cartões; jogo pegado com Gençlerbirliği lutando contra queda e Kasimpaşa físico.",
    keyPoints: [
      "Liga turca média 1.8 cartões/jogo acima de europeias.",
      "Gençlerbirliği briga contra rebaixamento: 2.1 cartões/jogo.",
      "Árbitro local histórico 4.2 cartões/jogo.",
    ],
    validation: [
      "Monitorar escalações e árbitro confirmado.",
      "Stake 3% com gestão de risco padrão.",
    ],
    status: "Não iniciado",
  },
  "wba-sheffield-btts": {
    slug: "wba-sheffield-btts",
    match: "West Bromwich vs Sheffield United",
    title: "Ambos marcam",
    market: "BTTS",
    type: "Conservadora",
    odd: "1.68 - 1.88",
    confidence: "76%",
    stake: "3%",
    risk: "Baixo-Médio",
    time: "17h00",
    location: "The Hawthorns, Birmingham",
    summary: "Championship com alta taxa de BTTS; WBA marca em 75% em casa e Sheffield não se fecha fora.",
    keyPoints: [
      "WBA 1.4 g/jogo em casa; Sheffield 1.3 g/jogo fora.",
      "Histórico 60-75% BTTS recente entre os clubes.",
      "Defesas concedem 1.1-1.2 g/jogo.",
    ],
    validation: [
      "Checar condições climáticas e gramado.",
      "Stake 3% com confiança 76%.",
    ],
    status: "Não iniciado",
  },
  "union-leipzig-escanteios": {
    slug: "union-leipzig-escanteios",
    match: "Union Berlin vs RB Leipzig",
    title: "Over 9.5 escanteios",
    market: "Mais de 9.5 cantos",
    type: "Conservadora",
    odd: "1.72 - 1.92",
    confidence: "79%",
    stake: "3%",
    risk: "Baixo-Médio",
    time: "16h30",
    location: "An der Alten Försterei, Berlim",
    summary: "Union usa jogo lateral e Leipzig bloqueia; expectativa de 9.5-11 cantos.",
    keyPoints: [
      "Union 5+ cantos/jogo em casa; Leipzig 4-5 como visitante.",
      "Estilos cruzados geram bloqueios e bolas aéreas.",
      "Árbitro permissivo aumenta volume de cantos.",
    ],
    validation: [
      "Confirmar escalações com pontas titulares.",
      "Linha válida se mantida em 9.5; stake 3%.",
    ],
    status: "Não iniciado",
  },
  "lecce-pisa-under-corners": {
    slug: "lecce-pisa-under-corners",
    match: "Lecce vs Pisa",
    title: "Under 10.5 escanteios",
    market: "Menos de 10.5 cantos",
    type: "Arrojada",
    odd: "1.78 - 1.98",
    confidence: "74%",
    stake: "2.5%",
    risk: "Médio",
    time: "16h45",
    location: "Via del Mare, Lecce",
    summary: "Jogo tende a ser fechado: Serie A gera menos cantos e ambos os times jogam compactos.",
    keyPoints: [
      "Serie A média ~8.2 cantos/jogo.",
      "Lecce 5.1 cantos/jogo; Pisa 4.8 fora.",
      "Ambos focam em não sofrer (luta contra rebaixamento).",
    ],
    validation: [
      "Evitar se linha cair <9.5; stake reduzida 2.5%.",
      "Checar vento/chuva que podem aumentar cantos.",
    ],
    status: "Não iniciado",
  },
  "raphinha-marcador": {
    slug: "raphinha-marcador",
    match: "Raphinha (Brasil)",
    title: "Raphinha marcar",
    market: "Marcar a qualquer tempo",
    type: "Arrojada",
    odd: "2.40 - 2.80",
    confidence: "72%",
    stake: "1%",
    risk: "Médio-Alto",
    time: "A confirmar",
    location: "Amistoso/qualificador (contexto sexta)",
    summary: "Entrada situacional: Raphinha vem em forma (4 gols em 5 jogos) e atua em papel ofensivo aberto.",
    keyPoints: [
      "Percentil 96 em criação e finalização recente pela seleção.",
      "Odds altas refletem variância; stake mínima controla risco.",
      "Depende de confirmação do jogo do Brasil na sexta.",
    ],
    validation: [
      "Só executar se jogo do Brasil confirmado e Raphinha titular.",
      "Stake 1% por variância alta de goleador.",
    ],
    status: "Não iniciado",
  },
  "sociedad-primeiro-tempo": {
    slug: "sociedad-primeiro-tempo",
    match: "Real Sociedad marca 1º tempo",
    title: "Sociedad marca primeiro",
    market: "Primeira meta da Sociedad",
    type: "Arrojada",
    odd: "1.80 - 2.00",
    confidence: "75%",
    stake: "2%",
    risk: "Médio",
    time: "17h00",
    location: "Reale Arena, San Sebastián",
    summary: "Sociedad costuma começar forte em casa (1.1 g/1T); Girona sofre 1.2 g/1T como visitante.",
    keyPoints: [
      "Pressão alta da Sociedad em casa gera gol cedo em 73% dos jogos.",
      "Girona chega traumatizado por goleada; defesa exposta no início.",
      "Mercado 1T com EV positivo dado o desequilíbrio emocional.",
    ],
    validation: [
      "Checar titulares ofensivos (Oyarzabal, Kubo).",
      "Stake 2% por ser mercado de tempo específico.",
    ],
    status: "Não iniciado",
  },
  "leipzig-clean-sheet": {
    slug: "leipzig-clean-sheet",
    match: "RB Leipzig não sofre gols",
    title: "Leipzig clean sheet",
    market: "Sem sofrer gols",
    type: "Arrojada",
    odd: "1.95 - 2.25",
    confidence: "73%",
    stake: "2.5%",
    risk: "Médio",
    time: "16h30",
    location: "An der Alten Försterei, Berlim",
    summary: "Defesa do Leipzig elite (0.6 g/jogo últimos 5); Union produz só 0.8 g/jogo.",
    keyPoints: [
      "Leipzig 40% clean sheets nos últimos 10 jogos.",
      "Union em queda, dificuldade de criação.",
      "Posse 65% prevista para Leipzig reduz volume ofensivo do Union.",
    ],
    validation: [
      "Confirmar linha defensiva titular (Orban/Lukeba).",
      "Stake 2.5% por risco de variância de clean sheet.",
    ],
    status: "Não iniciado",
  },
  "fluminense-vasco": {
    slug: "fluminense-vasco",
    match: "Fluminense vs Vasco",
    title: "Vitória Fluminense",
    market: "Moneyline Fluminense",
    type: "Conservadora",
    odd: "1.80 - 2.10",
    confidence: "83%",
    stake: "4%",
    risk: "Baixo-Médio",
    time: "20h00",
    location: "Maracanã, Rio de Janeiro",
    summary: "Jogo encerrado com surpresa negativa: Vasco virou nos acréscimos apesar do favoritismo do Flu e da sequência invicta.",
    keyPoints: [
      "Flu vinha de 30+ dias invicto e vitória 5-0 prévia; Vasco em 1/8 vitórias.",
      "Vasco respondeu psicologicamente e pressionou em casa (Maracanã).",
      "Gols: Serna (Flu), Rayan (VAS), Vegetti 90+3 (VAS) virando o jogo.",
      "Overconfidence identificado: confiança alta para cenário com inversão psicológica.",
    ],
    validation: [
      "Escalações confirmadas 1h antes; checar impacto psicológico reverso em casa.",
      "Para v2.0: reduzir stake 25% (4% → 3%) e confiança -5pp (83 → 78).",
      "Stop-loss 12% e Kelly 0.25 permanecem base de gestão.",
    ],
    status: "Encerrado · ❌ Perdida",
    finalScore: "Vasco 2 x 1 Fluminense",
    outcomeNotes: [
      "Vasco virou aos 90+3; dinâmica invertida expôs risco psicológico subestimado.",
      "Aplicar 8 variáveis v2.0: índice de anomalia ~45-50 teria sinalizado corte de stake/confiança.",
      "Lição: evitar overconfidence em clássicos com pressão de mandante."],
  },
  "aston-villa-basel": {
    slug: "aston-villa-basel",
    match: "Aston Villa vs Basel",
    title: "Villa + Over 1.5",
    market: "Vitória Aston Villa + Over 1.5 gols",
    type: "Conservadora",
    odd: "1.50 - 1.70",
    confidence: "86%",
    stake: "5%",
    risk: "Muito Baixo",
    time: "17h00",
    location: "St. Jakob Park, Basel",
    summary: "Aston Villa confirmou superioridade técnica fora de casa, vencendo apesar do susto inicial do Basel.",
    keyPoints: [
      "Disparidade financeira 500M vs 50M; EV sólido em odd ~1.60.",
      "Basel abriu o placar cedo, mas Villa virou no 2º tempo com Tielemans.",
      "Basel tinha 14 gols sofridos em 5 jogos; fragilidade defensiva exposta.",
      "Forma do Villa: 4V em 5 na UEL; ataque manteve consistência.",
    ],
    validation: [
      "Checar escalação 1h antes; stake 5% adequado ao EV identificado.",
      "Basel pressionado abriu espaços para transições do Villa.",
      "Kelly 0.25 aplicado; gestão alinhada ao risco muito baixo.",
    ],
    status: "Encerrado · ✅ Vencida",
    finalScore: "Basel 1 x 2 Aston Villa",
    outcomeNotes: [
      "Villa virou após sair atrás; domínio técnico prevaleceu.",
      "Retorno financeiro estimado: +8% com stake 5% e odd ~1.60.",
      "Confirma leitura de disparidade técnica como edge principal."],
  },
  "nottingham-utrecht": {
    slug: "nottingham-utrecht",
    match: "Nottingham Forest vs Utrecht",
    title: "Vitória Nottingham",
    market: "Moneyline Nottingham Forest",
    type: "Conservadora",
    odd: "1.65 - 1.90",
    confidence: "79%",
    stake: "3.5%",
    risk: "Baixo-Médio",
    time: "14h45",
    location: "Galgenwaard, Utrecht",
    summary: "Nottingham venceu fora, confirmando a disparidade técnica sobre um Utrecht em má fase.",
    keyPoints: [
      "Forest 500M vs Utrecht 100M; superioridade técnica clara.",
      "Utrecht sem vitórias em 5, ataque inoperante e defesa vulnerável.",
      "Cronologia: Kalimuendo 52' (NFO), Van der Hoorn 73' (UTC), Igor Jesus 88' (NFO).",
      "Visita compensada pela diferença de elenco e forma recente.",
    ],
    validation: [
      "Lineups 1h antes; manter stake 3.5%.",
      "Controlar exposição simultânea; stop-loss 12%.",
    ],
    status: "Encerrado · ✅ Vencida",
    finalScore: "Utrecht 1 x 2 Nottingham Forest",
    outcomeNotes: [
      "Forest venceu fora com gol decisivo aos 88'.",
      "Utrecht confirmou defesa frágil; disparidade técnica se manteve.",
      "Retorno estimado: +2.6% com stake 3.5%."],
  },
  "celtic-roma-btts": {
    slug: "celtic-roma-btts",
    match: "Celtic vs Roma",
    title: "BTTS + Over 2.5",
    market: "Ambos marcam + Over 2.5 gols",
    type: "Arrojada",
    odd: "1.85 - 2.15",
    confidence: "81%",
    stake: "2%",
    risk: "Médio",
    time: "17h00",
    location: "Celtic Park, Glasgow",
    summary: "Parlay BTTS+Over 2.5 falhou: Roma goleou 3-0 e o Celtic não marcou, invalidando o BTTS.",
    keyPoints: [
      "Over 2.5 acertou, mas BTTS não: Celtic zerado em casa.",
      "Novo técnico Wilfried Nancy estreou mal; volatilidade alta ignorada.",
      "Pressão psicológica do Celtic não se traduziu em ataque efetivo.",
      "Parlay exige duas condições; risco elevado com técnico estreante.",
    ],
    validation: [
      "Checar desfalques (Johnston, Jota) 1h antes.",
      "Para v2.0: reduzir stake 50% ou rejeitar com técnico novo e parlay.",
      "Kelly 0.25 e stop-loss 12% mantidos, mas inadequados ao risco real.",
    ],
    status: "Encerrado · ❌ Perdida",
    finalScore: "Celtic 0 x 3 Roma",
    outcomeNotes: [
      "BTTS falhou apesar do Over 2.5; Roma controlou o jogo.",
      "Índice de anomalia v2.0 (50+) teria rejeitado a entrada.",
      "Parlay amplificou risco; lição: evitar com técnico estreante."],
  },
  "betis-zagreb": {
    slug: "betis-zagreb",
    match: "Real Betis vs Dinamo Zagreb",
    title: "Vitória Betis",
    market: "Moneyline Betis",
    type: "Conservadora",
    odd: "1.70 - 1.95",
    confidence: "85%",
    stake: "4%",
    risk: "Baixo-Médio",
    time: "14h45",
    location: "Estádio Maksimir, Zagreb",
    summary: "Betis confirmou favoritismo, abrindo 3-0 no 1º tempo e controlando o jogo em Zagreb.",
    keyPoints: [
      "Disparidade técnica Betis 500M+ vs Zagreb 50M+.",
      "Cronologia: OG Zagreb 31', Riquelme 34', Antony 38' (3-0 HT); Zagreb 80'.",
      "Zagreb exposto pela necessidade de vencer; defesa permeável.",
      "Pellegrini experiente superou equipe em crise; EV manteve-se alto.",
    ],
    validation: [
      "Checar suspensões/lesões (Rodríguez, Firpo, Bellerín, Isco).",
      "Stake 4% adequado; stop-loss 12% mantido.",
      "Kelly 0.25 aplicado; gestão consistente com confiança 85%.",
    ],
    status: "Encerrado · ✅ Vencida",
    finalScore: "Dinamo Zagreb 1 x 3 Real Betis",
    outcomeNotes: [
      "Vitória tranquila com 3-0 no 1º tempo; pressão de Zagreb não surtiu efeito.",
      "Retorno estimado: +3.3% com stake 4% e odd ~1.82.",
      "Confirma tese de disparidade técnica como principal edge."],
  },
  "flamengo-pyramids": {
    slug: "flamengo-pyramids",
    match: "Flamengo vs Pyramids",
    title: "Flamengo + Over 2.5",
    market: "Vitória Flamengo + Over 2.5 gols",
    type: "Conservadora",
    odd: "1.45 - 1.65",
    confidence: "78%",
    stake: "3.5%",
    risk: "Baixo-Médio",
    time: "14h00",
    location: "Ahmad Bin Ali Stadium, Catar (neutro)",
    summary: "Flamengo campeão da Libertadores com ataque em forma encara Pyramids após goleada 6-1 e defesa frágil.",
    keyPoints: [
      "Arrascaeta 2 gols vs Cruz Azul; ataque com BH, Lino, Carrascal.",
      "Pyramids sofreu 6-1; nível técnico abaixo; moral baixa.",
      "Over 2.5 em 70% dos cenários; disparidade ofensiva clara.",
      "Campo neutro reduz fator casa, mas favorece superioridade técnica.",
    ],
    validation: [
      "Confirmar escalação 1h antes; foco de Filipe Luís na final.",
      "Controlar stake 3.5% e gestão de variância.",
    ],
  },
  "zagreb-betis-parlay": {
    slug: "zagreb-betis-parlay",
    match: "Dinamo Zagreb vs Betis",
    title: "Parlay cartões + Betis",
    market: "Over 4.5 cartões + Vitória Betis",
    type: "Arrojada",
    odd: "1.90 - 2.25",
    confidence: "80%",
    stake: "2%",
    risk: "Médio",
    time: "14h45",
    location: "Maksimir, Zagreb",
    summary: "Parlay confirmou vitória do Betis e over 4.5 cartões em jogo tenso e pegado em Zagreb.",
    keyPoints: [
      "Vitória Betis 3-1 já aos 45'; Betis dominante.",
      "Cartões estimados 5-7 pelo perfil do árbitro e pressão croata.",
      "Linha 4.5 manteve valor com jogo físico e faltoso.",
      "Combina favoritismo Betis (85%) com linha de cartões (75%).",
    ],
    validation: [
      "Stake 2% (Kelly 0.25) por risco combinado.",
      "Monitorar linha de cartões pré-jogo; ajustar se cair abaixo de 4.5.",
    ],
    status: "Encerrado · ✅ Vencida (cartões 5-7 estim.)",
    finalScore: "Betis 3-1; over 4.5 cartões",
    outcomeNotes: [
      "Parlay confirmada: vitória Betis + over cartões (estimado 5-7).",
      "Jogo físico manteve média de faltas; árbitro condizente com expectativa.",
      "Retorno estimado: +4% com stake 2%."],
  },
  "roma-primeiro-tempo": {
    slug: "roma-primeiro-tempo",
    match: "Celtic vs Roma",
    title: "Roma marca no 1º tempo",
    market: "Primeira meta da Roma",
    type: "Conservadora",
    odd: "1.55 - 1.75",
    confidence: "76%",
    stake: "3%",
    risk: "Baixo-Médio",
    time: "17h00",
    location: "Celtic Park, Glasgow",
    summary: "Roma marcou cedo e dominou o 1º tempo, validando a tese de entrada forte em transição ofensiva.",
    keyPoints: [
      "Cronologia: OG 6', Ferguson 36', Ferguson 45+1' (3-0 HT).",
      "Celtic desorganizado com técnico novo; espaços para contra-ataque.",
      "Roma historicamente marca antes dos 35' na UEL recente.",
      "Mercado 1T manteve EV com confiança 76%.",
    ],
    validation: [
      "Lineups 1h antes; checar titulares de criação (Pellegrini/Soulé).",
      "Stake 3% com stop-loss 12% consistente com confiança média.",
    ],
    status: "Encerrado · ✅ Vencida",
    finalScore: "Roma 3-0 antes do intervalo",
    outcomeNotes: [
      "Gol aos 6' abriu caminho; 3-0 no HT confirmou tese de entrada rápida.",
      "Retorno estimado: +1.95% com stake 3% e odd ~1.65.",
      "Valida leitura de transição ofensiva romana."],
  },
  "lo-celso-marcador": {
    slug: "lo-celso-marcador",
    match: "Celtic vs Roma",
    title: "Lo Celso marcar a qualquer tempo",
    market: "Marcador (Lo Celso)",
    type: "Arrojada",
    odd: "2.50 - 3.20",
    confidence: "84%",
    stake: "1%",
    risk: "Médio-Alto",
    time: "17h00",
    location: "Celtic Park, Glasgow",
    summary: "Aposta de goleador não bateu: Lo Celso jogou mais recuado e não marcou na goleada romana.",
    keyPoints: [
      "Roma já vencia 3-0 no 1º tempo, reduzindo necessidade de avanço de Lo Celso.",
      "Mercado de artilheiro tem alta variância; posição foi mais defensiva.",
      "Odds 2.5-3.2 refletiam baixa probabilidade; risco assumido com stake 1%.",
      "Defesa frágil do Celtic não converteu em gol do meio-campista.",
    ],
    validation: [
      "Stake 1% (Kelly 0.25) por ser mercado de goleador.",
      "Confirmar titularidade 1h antes; evitar se recuo tático previsto.",
    ],
    status: "Encerrado · ❌ Perdida",
    finalScore: "Celtic 0 x 3 Roma",
    outcomeNotes: [
      "Lo Celso não marcou; posicionamento recuado limitou finalizações.",
      "Mesmo com vitória larga, papel defensivo manteve xG individual baixo.",
      "Perda controlada pela stake de 1%."],
  },
  "celtic-roma-escanteios": {
    slug: "celtic-roma-escanteios",
    match: "Celtic vs Roma",
    title: "Over 9.5 escanteios",
    market: "Mais de 9.5 escanteios",
    type: "Conservadora",
    odd: "1.65 - 1.85",
    confidence: "77%",
    stake: "3%",
    risk: "Baixo-Médio",
    time: "17h00",
    location: "Celtic Park, Glasgow",
    summary: "Linha de escanteios bateu: jogo aberto com Celtic pressionando mesmo perdendo e Roma bloqueando cruzamentos.",
    keyPoints: [
      "Celtic buscou reação e gerou cantos; Roma cedeu bloqueios.",
      "Histórico sustentou expectativa de 11-12 escanteios; linha 9.5 foi superada.",
      "Goleada não reduziu volume ofensivo do mandante.",
      "Mercado manteve EV com confiança 77% e stake 3%.",
    ],
    validation: [
      "Monitorar linha se cair abaixo de 9.5; ajustar stake se subir muito.",
      "Manter stake 3% com stop-loss diário 12%.",
    ],
    status: "Encerrado · ✅ Vencida",
    finalScore: "Celtic 0 x 3 Roma; total estimado 11-12 escanteios",
    outcomeNotes: [
      "Pressão do Celtic mesmo em desvantagem sustentou volume de cantos.",
      "Roma cedeu escanteios via bloqueios; linha 9.5 superada.",
      "Retorno estimado: +2.25% com stake 3%."],
  },
};
